/**
 * Owner screen copy in the pilot languages — PRD Part I B01, E10-S05.
 *
 * "Offer local-language selection." / "Owner can submit details and evidence
 * in selected pilot languages."
 *
 * The Tamil strings were written for this build and need a review by a
 * native speaker before the pilot. Messages produced by the server (for
 * example validation errors) are still English.
 */

export type OwnerLocale = 'en-IN' | 'ta-IN';

const en = {
  shellTitle: 'Dream Destination · For businesses',
  navListings: 'My listings',
  navRegister: 'Register a business',
  backToApp: 'Back to Dream Destination',
  language: 'Language',
  signInTitle: 'Sign in to manage a business',
  signInBody: 'Business listings belong to an account, so you need to be signed in to register or update one.',
  signInAction: 'Go to sign-in',

  // B01
  startTitle: 'List your business on Dream Destination',
  startLead: 'Travellers planning trips to Coimbatore and the Nilgiris see verified local businesses near the places they visit.',
  eligibilityTitle: 'Who can list',
  eligibility: [
    'A business that serves visitors in a pilot area: a place to eat, stay, shop, learn a craft, visit a farm, or hire a guide or vehicle.',
    'You own the business or are responsible for running it.',
    'You can show a registration or licence for the type of business, and proof of its address.',
  ],
  requiredTitle: 'What you will need',
  required: [
    'Name, address and PIN code, and the entrance marked on a map',
    'A phone number travellers can call, and the name of the person responsible',
    'Opening hours, price band, payment methods and accessibility',
    'A photo of a registration or licence, and an address proof',
  ],
  verificationTitle: 'How verification works',
  verification:
    'A reviewer checks ownership, address, business type, hours and contact against what you upload, and may call you. It usually takes up to five working days. Your listing is not shown to travellers until it is approved.',
  dataTitle: 'What we do with your information',
  data: [
    'Your listing details are shown to travellers once approved.',
    'Evidence documents are seen only by you and the review team. They are never shown to travellers.',
    'We count how travellers interact with your listing and show you those counts. We do not sell your data.',
  ],
  startFormTitle: 'Start your listing',
  businessName: 'Business name',
  area: 'Area',
  areaHelp: 'You will place the exact map pin in the next step.',
  startAction: 'Start listing',
  starting: 'Starting…',
  progressSaved: 'Your progress is saved as you go. You can come back any time.',

  // Steps
  stepDetails: 'Details',
  stepEvidence: 'Evidence',
  stepPreview: 'Preview and send',

  // B02
  detailsTitle: 'Business details',
  sectionBasics: 'About the business',
  sectionLocation: 'Location',
  sectionContact: 'Contact',
  sectionHours: 'Opening hours',
  sectionOffer: 'Prices, services and payment',
  sectionAccess: 'Accessibility',
  sectionPhotos: 'Photos',
  category: 'Category',
  chooseCategory: 'Choose a category',
  description: 'Short description',
  descriptionHelp: 'One or two sentences about what travellers will find. Up to 400 characters.',
  addressLine: 'Street address',
  locality: 'Village, town or locality',
  pin: 'PIN code',
  latitude: 'Latitude',
  longitude: 'Longitude',
  locationHelp: 'Open the map, find your entrance, and copy its latitude and longitude here.',
  openMap: 'Open the map at this point',
  phone: 'Phone travellers can call',
  ownerName: 'Person responsible for the listing',
  closed: 'Closed',
  opens: 'Opens',
  closes: 'Closes',
  priceBand: 'Price band',
  priceBandNone: 'Not set',
  services: 'Services',
  servicesHelp: 'Separate each with a comma, such as “Tasting, Takeaway”.',
  payments: 'Payment methods',
  stepFree: 'Is the entrance step-free?',
  accessibleToilet: 'Is there an accessible toilet?',
  yes: 'Yes',
  no: 'No',
  notSure: 'Not sure',
  accessNote: 'Anything else about access',
  saving: 'Saving…',
  savedAt: 'Saved at',
  saveFailed: 'Not saved. Check the highlighted fields.',
  continueToEvidence: 'Continue to evidence',

  // B03
  evidenceTitle: 'Verification evidence',
  evidenceLead: 'Upload the documents asked for below. Photos taken on a phone are fine if every word is readable.',
  accepted: 'Accepted: PDF, JPEG, PNG or WebP, up to 5 MB each. PDFs with scripts or attached files are refused.',
  privacy: 'Only you and the review team can open these files. They are never shown to travellers.',
  reviewTime: 'Review usually takes up to five working days after you send the listing.',
  chooseCategoryFirst: 'Choose a category on the details page first, so we know which documents to ask for.',
  upload: 'Upload',
  uploading: 'Uploading…',
  remove: 'Remove',
  uploaded: 'Uploaded',
  continueToPreview: 'Continue to preview',

  // B04
  previewTitle: 'Preview your listing',
  previewLead: 'This is exactly how travellers will see your listing once it is approved.',
  gapsTitle: 'Missing before you can send',
  adviceTitle: 'Recommended',
  noGaps: 'Everything a traveller relies on is filled in.',
  sendForReview: 'Send for review',
  sending: 'Sending…',
  sent: 'Sent for review. We will let you know the decision here.',
  editDetails: 'Edit details',

  // B05
  listingsTitle: 'Your listings',
  noListings: 'You have not listed a business yet.',
  status: 'Status',
  statusLabels: {
    draft: 'Draft — not sent yet',
    pending: 'In review',
    changes_requested: 'Changes requested',
    active: 'Live',
    suspended: 'Hidden while a report is checked',
    rejected: 'Not approved',
    expired: 'Expired',
  } as Record<string, string>,
  open: 'Open',
  requiredUpdates: 'What needs your attention',
  nothingNeeded: 'Nothing needs your attention.',
  activityTitle: 'Traveller activity in the last 30 days',
  activityDisclaimer:
    'These count actions travellers took on Dream Destination. They are not bookings or sales, and we cannot tell whether a visit followed.',
  demoActivity: 'Includes simulated demonstration activity, not real travellers.',
  notMeasured: 'Not measured',
  reportsTitle: 'Reports from travellers',
  reportsLead: 'Travellers can report a problem with a listing. You see what was reported, never who reported it.',
  yourResponse: 'Your response',
  respond: 'Send response',
  responded: 'Response sent to the operations team.',
  confirmDetails: 'My details are still correct',
  confirmed: 'Thank you. Travellers will see your details as confirmed today.',
  updateListing: 'Update listing',
  previewListing: 'Preview',
  continueSetup: 'Continue setting up',
  sponsorshipTitle: 'Sponsored placement',
  sponsorshipBody:
    'Sponsored listings carry a visible “Sponsored” label. Sponsorship never changes verification, ranking of destinations, or any Dream Score.',
  requestSponsorship: 'Ask about sponsored placement',
  sponsorshipRequested: 'Your request is with the review team.',
  sponsorshipActive: 'This listing is sponsored.',
  sponsorshipNeedsVerification: 'Available once your listing is verified.',

  // B06
  updatesTitle: 'Update your listing',
  updatesLead: 'Changes to hours, price, contact and services show to travellers straight away.',
  rapidTitle: 'Hours, price and contact',
  saveChanges: 'Save changes',
  changesSaved: 'Saved. Travellers now see the new details.',
  closureTitle: 'Temporary closure',
  closureLead: 'Closed for a holiday, repairs or a family event? Travellers will see the dates and your listing is left out of suggestions while closed.',
  closedFrom: 'First closed day',
  reopens: 'Last closed day',
  closureNote: 'Note for travellers (optional)',
  setClosure: 'Save closure',
  clearClosure: 'Remove closure',
  availabilityTitle: 'Availability',
  availabilityLead: 'A short note such as “Two rooms free this weekend”. Up to 140 characters.',
  saveAvailability: 'Save availability',
  sensitiveTitle: 'Name, address, map pin or owner',
  sensitiveLead:
    'These changes are checked by a reviewer before travellers see them, because they can send travellers to a different place or hand the listing to someone else.',
  changeReason: 'Why is this change needed?',
  requestChange: 'Send change for review',
  changeRequested: 'Sent for review. Travellers see the current details until it is approved.',
  changePending: 'A change is already waiting for review.',
};

export type OwnerCopy = typeof en;

const ta: OwnerCopy = {
  shellTitle: 'ட்ரீம் டெஸ்டினேஷன் · வணிகங்களுக்கு',
  navListings: 'என் பட்டியல்கள்',
  navRegister: 'வணிகத்தைப் பதிவு செய்க',
  backToApp: 'ட்ரீம் டெஸ்டினேஷனுக்குத் திரும்பு',
  language: 'மொழி',
  signInTitle: 'வணிகத்தை நிர்வகிக்க உள்நுழைக',
  signInBody: 'வணிகப் பட்டியல் ஒரு கணக்குக்குச் சொந்தமானது. பதிவு செய்ய அல்லது புதுப்பிக்க உள்நுழைய வேண்டும்.',
  signInAction: 'உள்நுழையச் செல்க',

  startTitle: 'உங்கள் வணிகத்தை ட்ரீம் டெஸ்டினேஷனில் பட்டியலிடுங்கள்',
  startLead: 'கோயம்புத்தூர் மற்றும் நீலகிரிக்குப் பயணம் திட்டமிடும் பயணிகள், அவர்கள் செல்லும் இடங்களுக்கு அருகிலுள்ள சரிபார்க்கப்பட்ட உள்ளூர் வணிகங்களைப் பார்க்கிறார்கள்.',
  eligibilityTitle: 'யார் பட்டியலிடலாம்',
  eligibility: [
    'முன்னோட்டப் பகுதியில் பயணிகளுக்குச் சேவை செய்யும் வணிகம்: உணவகம், தங்குமிடம், கடை, கைவினைப் பயிற்சி, பண்ணை, வழிகாட்டி அல்லது வாகன சேவை.',
    'நீங்கள் அந்த வணிகத்தின் உரிமையாளர் அல்லது அதை நடத்தும் பொறுப்பாளர்.',
    'வணிக வகைக்கான பதிவு அல்லது உரிமம், மற்றும் முகவரிச் சான்றைக் காட்ட முடியும்.',
  ],
  requiredTitle: 'உங்களுக்குத் தேவையானவை',
  required: [
    'பெயர், முகவரி, அஞ்சல் குறியீடு, மற்றும் வரைபடத்தில் நுழைவாயிலின் இடம்',
    'பயணிகள் அழைக்கக்கூடிய தொலைபேசி எண், மற்றும் பொறுப்பாளரின் பெயர்',
    'திறந்திருக்கும் நேரம், விலை நிலை, பணம் செலுத்தும் முறைகள், அணுகல் வசதி',
    'பதிவு அல்லது உரிமத்தின் புகைப்படம், மற்றும் முகவரிச் சான்று',
  ],
  verificationTitle: 'சரிபார்ப்பு எப்படி நடக்கிறது',
  verification:
    'நீங்கள் பதிவேற்றியவற்றைக் கொண்டு ஒரு மதிப்பாய்வாளர் உரிமை, முகவரி, வணிக வகை, நேரம், தொடர்பு ஆகியவற்றைச் சரிபார்ப்பார்; உங்களை அழைக்கவும் கூடும். பொதுவாக ஐந்து வேலை நாட்கள் வரை ஆகும். ஒப்புதல் கிடைக்கும் வரை உங்கள் பட்டியல் பயணிகளுக்குக் காட்டப்படாது.',
  dataTitle: 'உங்கள் தகவலை நாங்கள் என்ன செய்கிறோம்',
  data: [
    'ஒப்புதலுக்குப் பிறகு உங்கள் பட்டியல் விவரங்கள் பயணிகளுக்குக் காட்டப்படும்.',
    'சான்று ஆவணங்களை நீங்களும் மதிப்பாய்வுக் குழுவும் மட்டுமே பார்க்க முடியும். அவை பயணிகளுக்கு ஒருபோதும் காட்டப்படாது.',
    'பயணிகள் உங்கள் பட்டியலுடன் எப்படி ஈடுபடுகிறார்கள் என்பதை எண்ணி உங்களுக்குக் காட்டுகிறோம். உங்கள் தரவை நாங்கள் விற்பதில்லை.',
  ],
  startFormTitle: 'உங்கள் பட்டியலைத் தொடங்குங்கள்',
  businessName: 'வணிகத்தின் பெயர்',
  area: 'பகுதி',
  areaHelp: 'அடுத்த படியில் வரைபடத்தில் சரியான இடத்தைக் குறிப்பீர்கள்.',
  startAction: 'பட்டியலைத் தொடங்கு',
  starting: 'தொடங்குகிறது…',
  progressSaved: 'நீங்கள் நிரப்பும்போதே உங்கள் முன்னேற்றம் சேமிக்கப்படுகிறது. எப்போது வேண்டுமானாலும் திரும்பி வரலாம்.',

  stepDetails: 'விவரங்கள்',
  stepEvidence: 'சான்றுகள்',
  stepPreview: 'முன்னோட்டம் மற்றும் அனுப்புதல்',

  detailsTitle: 'வணிக விவரங்கள்',
  sectionBasics: 'வணிகத்தைப் பற்றி',
  sectionLocation: 'இருப்பிடம்',
  sectionContact: 'தொடர்பு',
  sectionHours: 'திறந்திருக்கும் நேரம்',
  sectionOffer: 'விலை, சேவைகள், பணம் செலுத்துதல்',
  sectionAccess: 'அணுகல் வசதி',
  sectionPhotos: 'புகைப்படங்கள்',
  category: 'வகை',
  chooseCategory: 'ஒரு வகையைத் தேர்ந்தெடுக்கவும்',
  description: 'சுருக்கமான விளக்கம்',
  descriptionHelp: 'பயணிகள் இங்கே என்ன காண்பார்கள் என்பது பற்றி ஓரிரு வாக்கியங்கள். 400 எழுத்துகள் வரை.',
  addressLine: 'தெரு முகவரி',
  locality: 'கிராமம், நகரம் அல்லது பகுதி',
  pin: 'அஞ்சல் குறியீடு (PIN)',
  latitude: 'அட்சரேகை',
  longitude: 'தீர்க்கரேகை',
  locationHelp: 'வரைபடத்தைத் திறந்து உங்கள் நுழைவாயிலைக் கண்டுபிடித்து, அதன் அட்சரேகை, தீர்க்கரேகையை இங்கே நகலெடுக்கவும்.',
  openMap: 'இந்த இடத்தில் வரைபடத்தைத் திற',
  phone: 'பயணிகள் அழைக்கக்கூடிய தொலைபேசி',
  ownerName: 'பட்டியலுக்குப் பொறுப்பானவர்',
  closed: 'விடுமுறை',
  opens: 'திறக்கும் நேரம்',
  closes: 'மூடும் நேரம்',
  priceBand: 'விலை நிலை',
  priceBandNone: 'அமைக்கப்படவில்லை',
  services: 'சேவைகள்',
  servicesHelp: 'ஒவ்வொன்றையும் காற்புள்ளியால் பிரிக்கவும், எ.கா. “சுவைத்தல், பார்சல்”.',
  payments: 'பணம் செலுத்தும் முறைகள்',
  stepFree: 'நுழைவாயிலில் படிகள் இல்லையா?',
  accessibleToilet: 'மாற்றுத்திறனாளிகள் பயன்படுத்தக்கூடிய கழிப்பறை உள்ளதா?',
  yes: 'ஆம்',
  no: 'இல்லை',
  notSure: 'தெரியவில்லை',
  accessNote: 'அணுகல் பற்றிய வேறு தகவல்',
  saving: 'சேமிக்கிறது…',
  savedAt: 'சேமிக்கப்பட்ட நேரம்',
  saveFailed: 'சேமிக்கப்படவில்லை. குறிக்கப்பட்ட புலங்களைச் சரிபார்க்கவும்.',
  continueToEvidence: 'சான்றுகளுக்குத் தொடர்க',

  evidenceTitle: 'சரிபார்ப்புச் சான்றுகள்',
  evidenceLead: 'கீழே கேட்கப்பட்ட ஆவணங்களைப் பதிவேற்றவும். ஒவ்வொரு சொல்லும் படிக்கக்கூடியதாக இருந்தால் கைபேசிப் புகைப்படம் போதும்.',
  accepted: 'ஏற்கப்படுபவை: PDF, JPEG, PNG அல்லது WebP, ஒவ்வொன்றும் 5 MB வரை. ஸ்கிரிப்ட் அல்லது இணைப்புக் கோப்புகள் உள்ள PDF ஏற்கப்படாது.',
  privacy: 'இந்தக் கோப்புகளை நீங்களும் மதிப்பாய்வுக் குழுவும் மட்டுமே திறக்க முடியும். அவை பயணிகளுக்கு ஒருபோதும் காட்டப்படாது.',
  reviewTime: 'பட்டியலை அனுப்பிய பிறகு மதிப்பாய்வுக்குப் பொதுவாக ஐந்து வேலை நாட்கள் வரை ஆகும்.',
  chooseCategoryFirst: 'எந்த ஆவணங்கள் தேவை என்பதை அறிய, முதலில் விவரங்கள் பக்கத்தில் ஒரு வகையைத் தேர்ந்தெடுக்கவும்.',
  upload: 'பதிவேற்று',
  uploading: 'பதிவேற்றுகிறது…',
  remove: 'நீக்கு',
  uploaded: 'பதிவேற்றப்பட்டது',
  continueToPreview: 'முன்னோட்டத்துக்குத் தொடர்க',

  previewTitle: 'உங்கள் பட்டியலின் முன்னோட்டம்',
  previewLead: 'ஒப்புதலுக்குப் பிறகு பயணிகள் உங்கள் பட்டியலைச் சரியாக இப்படித்தான் பார்ப்பார்கள்.',
  gapsTitle: 'அனுப்புவதற்கு முன் நிரப்ப வேண்டியவை',
  adviceTitle: 'பரிந்துரைக்கப்படுபவை',
  noGaps: 'பயணிகள் நம்பியிருக்கும் அனைத்தும் நிரப்பப்பட்டுள்ளன.',
  sendForReview: 'மதிப்பாய்வுக்கு அனுப்பு',
  sending: 'அனுப்புகிறது…',
  sent: 'மதிப்பாய்வுக்கு அனுப்பப்பட்டது. முடிவை இங்கே தெரிவிப்போம்.',
  editDetails: 'விவரங்களைத் திருத்து',

  listingsTitle: 'உங்கள் பட்டியல்கள்',
  noListings: 'நீங்கள் இன்னும் எந்த வணிகத்தையும் பட்டியலிடவில்லை.',
  status: 'நிலை',
  statusLabels: {
    draft: 'வரைவு — இன்னும் அனுப்பவில்லை',
    pending: 'மதிப்பாய்வில் உள்ளது',
    changes_requested: 'மாற்றங்கள் கோரப்பட்டுள்ளன',
    active: 'நேரலையில் உள்ளது',
    suspended: 'புகார் சரிபார்க்கப்படும் வரை மறைக்கப்பட்டுள்ளது',
    rejected: 'ஒப்புதல் அளிக்கப்படவில்லை',
    expired: 'காலாவதியானது',
  },
  open: 'திற',
  requiredUpdates: 'உங்கள் கவனம் தேவைப்படுபவை',
  nothingNeeded: 'உங்கள் கவனம் தேவைப்படுவது எதுவும் இல்லை.',
  activityTitle: 'கடந்த 30 நாட்களில் பயணிகளின் செயல்பாடு',
  activityDisclaimer:
    'இவை ட்ரீம் டெஸ்டினேஷனில் பயணிகள் செய்த செயல்களின் எண்ணிக்கை. இவை முன்பதிவுகளோ விற்பனையோ அல்ல; அதன் பிறகு வருகை நடந்ததா என்பது எங்களுக்குத் தெரியாது.',
  demoActivity: 'உண்மையான பயணிகள் அல்லாத, உருவகப்படுத்தப்பட்ட செயல்விளக்கச் செயல்பாடும் இதில் அடங்கும்.',
  notMeasured: 'அளவிடப்படவில்லை',
  reportsTitle: 'பயணிகளின் புகார்கள்',
  reportsLead: 'ஒரு பட்டியலில் உள்ள பிரச்சினையைப் பயணிகள் தெரிவிக்கலாம். என்ன தெரிவிக்கப்பட்டது என்பதைப் பார்ப்பீர்கள்; யார் தெரிவித்தார் என்பதை அல்ல.',
  yourResponse: 'உங்கள் பதில்',
  respond: 'பதிலை அனுப்பு',
  responded: 'பதில் செயல்பாட்டுக் குழுவுக்கு அனுப்பப்பட்டது.',
  confirmDetails: 'என் விவரங்கள் இன்னும் சரியாக உள்ளன',
  confirmed: 'நன்றி. உங்கள் விவரங்கள் இன்று உறுதிசெய்யப்பட்டதாகப் பயணிகள் பார்ப்பார்கள்.',
  updateListing: 'பட்டியலைப் புதுப்பி',
  previewListing: 'முன்னோட்டம்',
  continueSetup: 'அமைப்பைத் தொடர்க',
  sponsorshipTitle: 'விளம்பர இடம்',
  sponsorshipBody:
    'விளம்பரப் பட்டியல்களில் “விளம்பரம்” என்ற குறி தெரியும்படி இருக்கும். விளம்பரம் சரிபார்ப்பையோ, இடங்களின் தரவரிசையையோ, எந்த ட்ரீம் ஸ்கோரையோ ஒருபோதும் மாற்றாது.',
  requestSponsorship: 'விளம்பர இடம் பற்றிக் கேளுங்கள்',
  sponsorshipRequested: 'உங்கள் கோரிக்கை மதிப்பாய்வுக் குழுவிடம் உள்ளது.',
  sponsorshipActive: 'இந்தப் பட்டியல் விளம்பரப் பட்டியலாக உள்ளது.',
  sponsorshipNeedsVerification: 'உங்கள் பட்டியல் சரிபார்க்கப்பட்ட பிறகு கிடைக்கும்.',

  updatesTitle: 'உங்கள் பட்டியலைப் புதுப்பிக்கவும்',
  updatesLead: 'நேரம், விலை, தொடர்பு, சேவைகள் ஆகியவற்றில் செய்யும் மாற்றங்கள் உடனே பயணிகளுக்குத் தெரியும்.',
  rapidTitle: 'நேரம், விலை மற்றும் தொடர்பு',
  saveChanges: 'மாற்றங்களைச் சேமி',
  changesSaved: 'சேமிக்கப்பட்டது. பயணிகள் இப்போது புதிய விவரங்களைப் பார்க்கிறார்கள்.',
  closureTitle: 'தற்காலிக மூடல்',
  closureLead: 'விடுமுறை, பழுதுபார்ப்பு அல்லது குடும்ப நிகழ்வுக்காக மூடுகிறீர்களா? பயணிகள் தேதிகளைப் பார்ப்பார்கள்; மூடியிருக்கும்போது உங்கள் பட்டியல் பரிந்துரைகளில் இடம்பெறாது.',
  closedFrom: 'மூடும் முதல் நாள்',
  reopens: 'மூடும் கடைசி நாள்',
  closureNote: 'பயணிகளுக்கான குறிப்பு (விருப்பத்தேர்வு)',
  setClosure: 'மூடலைச் சேமி',
  clearClosure: 'மூடலை நீக்கு',
  availabilityTitle: 'இருப்பு நிலை',
  availabilityLead: '“இந்த வார இறுதியில் இரண்டு அறைகள் காலி” போன்ற சிறு குறிப்பு. 140 எழுத்துகள் வரை.',
  saveAvailability: 'இருப்பு நிலையைச் சேமி',
  sensitiveTitle: 'பெயர், முகவரி, வரைபட இடம் அல்லது உரிமையாளர்',
  sensitiveLead:
    'இந்த மாற்றங்கள் பயணிகளை வேறு இடத்துக்கு அனுப்பவோ, பட்டியலை வேறொருவரிடம் ஒப்படைக்கவோ கூடும் என்பதால், பயணிகளுக்குத் தெரிவதற்கு முன் ஒரு மதிப்பாய்வாளர் சரிபார்ப்பார்.',
  changeReason: 'இந்த மாற்றம் ஏன் தேவை?',
  requestChange: 'மாற்றத்தை மதிப்பாய்வுக்கு அனுப்பு',
  changeRequested: 'மதிப்பாய்வுக்கு அனுப்பப்பட்டது. ஒப்புதல் கிடைக்கும் வரை பயணிகள் தற்போதைய விவரங்களையே பார்ப்பார்கள்.',
  changePending: 'ஒரு மாற்றம் ஏற்கனவே மதிப்பாய்வுக்காகக் காத்திருக்கிறது.',
};

const COPY: Record<OwnerLocale, OwnerCopy> = { 'en-IN': en, 'ta-IN': ta };

export function ownerCopy(locale: string | null | undefined): OwnerCopy {
  return locale === 'ta-IN' ? COPY['ta-IN'] : COPY['en-IN'];
}

export const CATEGORY_LABEL: Record<OwnerLocale, Record<string, string>> = {
  'en-IN': {
    restaurant: 'Restaurant',
    cafe: 'Cafe',
    homestay: 'Homestay',
    shop: 'Shop',
    artisan: 'Artisan or craft studio',
    farm: 'Farm',
    guide: 'Guide',
    transport: 'Transport',
  },
  'ta-IN': {
    restaurant: 'உணவகம்',
    cafe: 'சிற்றுண்டிச்சாலை',
    homestay: 'வீட்டுத் தங்குமிடம்',
    shop: 'கடை',
    artisan: 'கைவினைக் கூடம்',
    farm: 'பண்ணை',
    guide: 'வழிகாட்டி',
    transport: 'போக்குவரத்து',
  },
};
